# 5-6 실무팁 ( Code Function )
피처엔지니어링 작업을 함수화 하여, 선형적 작업을 최소화 한다.

func

In [1]:
##def add_ten(x) :
##    return x + 10

In [2]:
##add_ten(5)

src 디렉토리 생성 하고 다시 소스로 돌아와서.

In [3]:
# 위 함수 script 변수에 저장
script ="""
def add_ten(x) :
    return x + 10
"""

In [4]:
script

'\ndef add_ten(x) :\n    return x + 10\n'

In [5]:
filename = "./src/add_ten.py"   # ./ 현재폴더 아래       src 라는 디렉토리 안에    add_ten.py    로 저장.

In [6]:
# 파일로 생성하기
with open (filename, 'w') as file :
    file.write(script)

src  디렉토리에 add_ten.py 생성 된 것 확인.

test 파일에서 아래와 같이 작성.

In [7]:
import sys

In [8]:
sys.path.append('./src') # 현재 디렉토리 안의 src 패스 설정

In [9]:
from add_ten import add_ten # ( from 파일명 import 함수명)

In [10]:
add_ten(3)

13

In [11]:
## func 주피터노트북 파일 외부에서 생성, 그곳에 작성

In [12]:
## test 내용

In [13]:
import sys
import pandas as pd
import numpy as np

In [14]:
sys.path.append('./src')

In [15]:
dating_df = pd.read_csv('~/data/dating.csv') # new_dating.csv 라는 파일 없음

# 컬럼이름 변경

In [16]:
from col_rename import col_rename

In [17]:
dating_df = col_rename(dating_df)

# 결측치 처리

In [18]:
from missing_func import missing_func

In [19]:
dating_df = missing_func(dating_df)

# 이상치(Outlier) 처리

score 부분, 10으로 값 맞추기

In [20]:
from outlier_func import outlier_func

In [21]:
dating_df = outlier_func(dating_df)

In [22]:
pd.set_option('display.max_columns', 99)

In [23]:
dating_df.describe() # score max 10 적용 확인

,age,age_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match
count,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000,8130.000000
mean,26.034932,26.034932,3.776753,3.658303,22.320451,17.433629,20.266113,17.446224,10.705183,11.872082,3.803493,3.841882,3.757380,2.127983,-2.159533,-7.869065,22.320451,17.433629,20.266113,17.446224,10.705183,11.872082,3.803493,3.841882,3.757380,2.127983,-2.159533,-7.869065,0.198866,5.244649,-76.879090,3.270812,1.537761,0.164822
std,7.418562,7.418562,2.844297,2.807314,12.398470,7.017378,6.770061,6.068068,6.101937,6.351582,15.804916,18.622449,19.358834,20.888746,29.495408,34.942787,12.398470,7.017378,6.770061,6.068068,6.101937,6.351582,15.804916,18.622449,19.358834,20.888746,29.495408,34.942787,0.302338,5.697854,42.761973,17.230563,19.345369,0.371042
min,-99.000000,-99.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-0.830000,-99.000000,-99.000000,-99.000000,-99.000000,0.000000
25%,24.000000,24.000000,1.000000,1.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,5.000000,6.000000,6.000000,5.000000,5.000000,3.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,5.000000,6.000000,6.000000,5.000000,5.000000,3.000000,-0.010000,5.000000,-99.000000,5.000000,4.000000,0.000000
50%,26.000000,26.000000,3.000000,3.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.870000,6.000000,7.000000,7.000000,6.000000,7.000000,5.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.870000,6.000000,7.000000,7.000000,6.000000,7.000000,5.000000,0.220000,6.000000,-99.000000,6.000000,5.000000,0.000000
75%,28.000000,28.000000,6.000000,6.000000,25.000000,20.000000,23.260000,20.000000,15.000000,16.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,25.000000,20.000000,23.260000,20.000000,15.000000,16.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,0.430000,7.000000,-99.000000,7.000000,7.000000,0.000000
max,55.000000,55.000000,10.000000,10.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,0.910000,10.000000,20.000000,10.000000,10.000000,1.000000

important 부분 가중치 적용, 100 으로 값 맞추기

In [24]:
from imp_func import imp_func

In [25]:
dating_df = imp_func(dating_df)

Age 나이차 처리

In [26]:
from age_gap_func import age_gap_func

In [27]:
dating_df = age_gap_func(dating_df)

In [28]:
dating_df.head()

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match,age_gap,age_gap_dir
0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0,6.0,positive
1,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,0,1.0,positive
2,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,-99.0,1,1.0,positive
3,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,1,2.0,positive
4,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,1,3.0,positive

인종 처리

In [29]:
from race_func import race_func

In [30]:
dating_df = race_func(dating_df)

In [31]:
dating_df.head()

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match,age_gap,age_gap_dir,same_race,same_race_point
0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,0.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0,6.0,positive,-1,-2.0
1,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,0.0,0.0,40.0,0.0,0.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,0,1.0,positive,-1,-2.0
2,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,-99.0,1,1.0,positive,1,2.0
3,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,1,2.0,positive,-1,-2.0
4,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,1,3.0,positive,-1,-2.0

# 5-4 평가(Rating) 관련 피처 생성 및 활용

In [32]:
from rating_func import rating_func

In [33]:
dating_df = rating_func(dating_df)

In [34]:
dating_df.head()

,gender,age,age_o,race,race_o,importance_same_race,importance_same_religion,o_important_attractive,o_important_sincere,o_important_intelligence,o_important_funny,o_important_ambitious,o_important_shared_interests,o_score_attractive,o_score_sincere,o_score_intelligence,o_score_funny,o_score_ambitous,o_score_shared_interests,i_important_attractive,i_important_sincere,i_important_intellicence,i_important_funny,i_important_ambtition,i_important_shared_interests,i_score_attractive,i_score_sincere,i_score_intelligence,i_score_funny,i_score_ambition,i_score_shared_interests,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,match,age_gap,age_gap_dir,same_race,same_race_point,o_rating_attractive,o_rating_sincere,o_rating_intelligence,o_rating_funny,o_rating_ambitious,o_rating_shared_interests,i_rating_attractive,i_rating_sincere,i_rating_intellicence,i_rating_funny,i_rating_ambtition,i_rating_shared_interests,o_rating_total,i_rating_total,rating_mean
0,female,21.0,27.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,35.0,20.0,20.0,20.0,-99.0,5.0,6.0,8.0,8.0,8.0,8.0,6.0,15.0,20.0,20.0,15.0,15.0,15.0,6.0,9.0,7.0,7.0,6.0,5.0,0.14,3.0,2.0,7.0,6.0,0,6.0,positive,-1,-2.0,210.0,160.0,160.0,160.0,-99.0,30.0,90.0,180.0,140.0,105.0,90.0,75.0,144.000000,113.333333,126.839378
1,female,21.0,22.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,60.0,-99.0,-99.0,40.0,-99.0,-99.0,7.0,8.0,10.0,7.0,7.0,5.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,8.0,7.0,8.0,5.0,6.0,0.54,3.0,2.0,7.0,5.0,0,1.0,positive,-1,-2.0,420.0,-99.0,-99.0,280.0,-99.0,-99.0,105.0,160.0,140.0,120.0,75.0,90.0,350.000000,115.000000,173.118280
2,female,21.0,22.0,Asian/PacificIslander/Asian-American,Asian/PacificIslander/Asian-American,2.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,10.0,10.0,10.0,10.0,10.0,10.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,8.0,9.0,8.0,5.0,7.0,0.16,3.0,2.0,7.0,-99.0,1,1.0,positive,1,2.0,190.0,180.0,190.0,180.0,140.0,120.0,75.0,160.0,180.0,120.0,75.0,105.0,166.666667,119.166667,138.969874
3,female,21.0,23.0,Asian/PacificIslander/Asian-American,European/Caucasian-American,2.0,4.0,30.0,5.0,15.0,40.0,5.0,5.0,7.0,8.0,9.0,8.0,9.0,8.0,15.0,20.0,20.0,15.0,15.0,15.0,7.0,6.0,8.0,7.0,6.0,8.0,0.61,3.0,2.0,7.0,6.0,1,2.0,positive,-1,-2.0,210.0,40.0,135.0,320.0,45.0,40.0,105.0,120.0,160.0,105.0,90.0,120.0,131.666667,116.666667,123.713647
4,female,21.0,24.0,Asian/PacificIslander/Asian-American,Latino/HispanicAmerican,2.0,4.0,30.0,10.0,20.0,10.0,10.0,20.0,8.0,7.0,9.0,6.0,9.0,7.0,15.0,20.0,20.0,15.0,15.0,15.0,5.0,6.0,7.0,7.0,6.0,6.0,0.21,3.0,2.0,6.0,6.0,1,3.0,positive,-1,-2.0,240.0,70.0,180.0,60.0,90.0,140.0,75.0,120.0,140.0,105.0,90.0,90.0,130.000000,103.333333,115.142857

원하는 컬럼 추리기, 원핫 인코딩

In [35]:
from sel_one_func import sel_one_func

In [36]:
dating_df = sel_one_func(dating_df)

In [37]:
dating_df.head()

,age,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,age_gap,same_race_point,o_rating_attractive,o_rating_sincere,o_rating_intelligence,o_rating_funny,o_rating_ambitious,o_rating_shared_interests,i_rating_attractive,i_rating_sincere,i_rating_intellicence,i_rating_funny,i_rating_ambtition,i_rating_shared_interests,i_rating_total,o_rating_total,rating_mean,gender_female,gender_male,race_Asian/PacificIslander/Asian-American,race_Black/AfricanAmerican,race_European/Caucasian-American,race_Latino/HispanicAmerican,race_Other,age_gap_dir_negative,age_gap_dir_positive,age_gap_dir_zero
0,21.0,0.14,3.0,2.0,7.0,6.0,6.0,-2.0,210.0,160.0,160.0,160.0,-99.0,30.0,90.0,180.0,140.0,105.0,90.0,75.0,113.333333,144.000000,126.839378,1,0,1,0,0,0,0,0,1,0
1,21.0,0.54,3.0,2.0,7.0,5.0,1.0,-2.0,420.0,-99.0,-99.0,280.0,-99.0,-99.0,105.0,160.0,140.0,120.0,75.0,90.0,115.000000,350.000000,173.118280,1,0,1,0,0,0,0,0,1,0
2,21.0,0.16,3.0,2.0,7.0,-99.0,1.0,2.0,190.0,180.0,190.0,180.0,140.0,120.0,75.0,160.0,180.0,120.0,75.0,105.0,119.166667,166.666667,138.969874,1,0,1,0,0,0,0,0,1,0
3,21.0,0.61,3.0,2.0,7.0,6.0,2.0,-2.0,210.0,40.0,135.0,320.0,45.0,40.0,105.0,120.0,160.0,105.0,90.0,120.0,116.666667,131.666667,123.713647,1,0,1,0,0,0,0,0,1,0
4,21.0,0.21,3.0,2.0,6.0,6.0,3.0,-2.0,240.0,70.0,180.0,60.0,90.0,140.0,75.0,120.0,140.0,105.0,90.0,90.0,103.333333,130.000000,115.142857,1,0,1,0,0,0,0,0,1,0

# 위 ### import 부분들 func에 몰아 넣기

In [38]:
import sys
import pandas as pd
import numpy as np

In [39]:
sys.path.append('./src') # 현재 디렉토리 안의 src 패스 설정

In [40]:
dating_df = pd.read_csv('~/data/dating.csv') # new_dating.csv 라는 파일 없음

In [41]:
from pre_func import pre_func

In [42]:
pre_func(dating_df)

,age,interests_correlate,expected_happy_with_sd_people,expected_num_interested_in_me,like,guess_prob_liked,age_gap,same_race_point,o_rating_attractive,o_rating_sincere,o_rating_intelligence,o_rating_funny,o_rating_ambitious,o_rating_shared_interests,i_rating_attractive,i_rating_sincere,i_rating_intellicence,i_rating_funny,i_rating_ambtition,i_rating_shared_interests,i_rating_total,o_rating_total,rating_mean,gender_female,gender_male,race_Asian/PacificIslander/Asian-American,race_Black/AfricanAmerican,race_European/Caucasian-American,race_Latino/HispanicAmerican,race_Other,age_gap_dir_negative,age_gap_dir_positive,age_gap_dir_zero
0,21.0,0.14,3.0,2.0,7.0,6.0,6.0,-2.0,210.000000,160.000000,160.000000,160.000000,-99.000000,30.000000,90.0,180.0,140.0,105.0,90.0,75.0,113.333333,144.000000,126.839378,1,0,1,0,0,0,0,0,1,0
1,21.0,0.54,3.0,2.0,7.0,5.0,1.0,-2.0,420.000000,-99.000000,-99.000000,280.000000,-99.000000,-99.000000,105.0,160.0,140.0,120.0,75.0,90.0,115.000000,350.000000,173.118280,1,0,1,0,0,0,0,0,1,0
2,21.0,0.16,3.0,2.0,7.0,-99.0,1.0,2.0,190.000000,180.000000,190.000000,180.000000,140.000000,120.000000,75.0,160.0,180.0,120.0,75.0,105.0,119.166667,166.666667,138.969874,1,0,1,0,0,0,0,0,1,0
3,21.0,0.61,3.0,2.0,7.0,6.0,2.0,-2.0,210.000000,40.000000,135.000000,320.000000,45.000000,40.000000,105.0,120.0,160.0,105.0,90.0,120.0,116.666667,131.666667,123.713647,1,0,1,0,0,0,0,0,1,0
4,21.0,0.21,3.0,2.0,6.0,6.0,3.0,-2.0,240.000000,70.000000,180.000000,60.000000,90.000000,140.000000,75.0,120.0,140.0,105.0,90.0,90.0,103.333333,130.000000,115.142857,1,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8372,25.0,0.28,10.0,-99.0,4.0,4.0,1.0,1.0,80.000000,120.000000,210.000000,140.000000,120.000000,60.000000,490.0,-99.0,75.0,75.0,-99.0,-99.0,213.333333,121.666667,154.958541,0,1,0,0,1,0,0,0,1,0
8373,25.0,0.64,10.0,-99.0,2.0,5.0,1.0,-1.0,105.263158,52.631579,94.736842,42.105263,63.157895,78.947368,210.0,-99.0,75.0,75.0,-99.0,-99.0,120.000000,72.807018,90.627843,0,1,0,0,1,0,0,1,0,0
8374,25.0,0.71,10.0,-99.0,4.0,4.0,1.0,-1.0,300.000000,60.000000,70.000000,15.000000,70.000000,10.000000,280.0,-99.0,120.0,60.0,-99.0,-99.0,153.333333,87.500000,111.418685,0,1,0,0,1,0,0,0,1,0
8376,25.0,0.62,10.0,-99.0,5.0,5.0,3.0,-1.0,50.000000,175.000000,125.000000,50.000000,30.000000,120.000000,280.0,-99.0,75.0,60.0,-99.0,-99.0,138.333333,91.666667,110.265700,0,1,0,0,1,0,0,0,1,0
8377,25.0,0.01,10.0,-99.0,4.0,5.0,3.0,-1.0,160.000000,160.000000,70.000000,105.000000,35.000000,210.000000,210.0,-99.0,90.0,60.0,-99.0,-99.0,120.000000,123.333333,121.643836,0,1,0,0,1,0,0,0,1,0